#!/bin/sh

bspc config border_width        4
bspc config window_gap          35
bspc config top_padding         30
bspc config paddingless_monocle true
# bspc config bottom_padding      30
# bspc config left_padding        195
# bspc config right_padding       195

bspc config focused_border_color \#cf4c66
bspc config active_border_color \#cf4c66
bspc config normal_border_color \#333333

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5 6
