#!/bin/sh
# set aliases

alias l='ls --color'
alias la='ls -A --color'
alias ll='ls -lh --color'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../..'
alias c='clear'
alias n='ncmpcpp'
alias r='ranger'
alias i='dtach -A /tmp/irc-dtach weechat'
alias p="pwd | sed \"s:$HOME:~:g\""
alias e='$EDITOR'

alias gita='git add .'
alias gitc='git commit -m'
alias gitp='git push -u origin master'
alias gitt='git add . && git commit -m "<commit>" && git push -u origin master'

alias rm='rm -i'
alias ca='cava'
alias pac='pacaur --color=auto --noedit'
alias cmat='cmatrix -C red -an'
alias pacclean='sudo pacaur -R $(sudo pacaur -Qdtq)'
alias screenf="screenfetch -c1,5 -d '-gpu'"
