#!/bin/sh
# set aliases

lsargs='--color --group-directories-first'

# ls shorteners
alias l='ls ${lsargs}'
alias la='ls -A ${lsargs}'
alias ll='ls -lh ${lsargs}'

# shorteners
alias n='ncmpcpp'
alias r='ranger'
alias c='cava'
alias i='dtach -A /tmp/irc-dtach weechat'
alias p="pwd | sed \"s:$HOME:~:g\""
alias e='$EDITOR'
alias f='$EDITOR -c ":CtrlPMixed"'

# options
alias pac='pacaur --color=auto --noedit'
alias cmat='cmatrix -C red -an'
alias screenf="screenfetch -c1,5 -d '-gpu'"
alias rm='rm -i'

# git git git
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push -u origin master'
alias gt='git add . && git commit && git push -u origin master'

# misc
alias bt="wget http://cachefly.cachefly.net/100mb.test -O /dev/null"

# auto compile fonts
autofont()
{
    bdftopcf $1.bdf -o $1.pcf && \
        mkfontscale && \
        mkfontdir && \
        xset fp rehash && \
        fc-cache -fv
}

# quick access to config files
conf()
{
    case $1 in
        e|editor)
            $EDITOR ~/.config/nvim/init.vim ;;
        n|ncmpcpp)
            $EDITOR ~/.ncmpcpp/config ;;
        x|xrdb)
            $EDITOR ~/.Xresources ;;
        s|sxhkd|sxhkdrc)
            $EDITOR ~/.config/sxhkd/sxhkdrc ;;
        w|weechat)
            $EDITOR ~/.weechat/weechat.conf ;;
        t|tmux)
            $EDITOR ~/.tmux.conf ;;
        2|2bwm)
            $EDITOR ~/src/pkg/twobwm/config.h ;;
    esac
}

# source files and stuff
src()
{
    case $1 in
        shell|sh|s)
            source ~/.bashrc ;;
        xrdb|x)
            xrdb ~/.Xresources ;;
        2bwm|2)
            prev=$(pwd) && \
            cd ~/src/pkg/twobwm && \
            make && sudo make install && \
            cd $prev ;;
    esac
}

# ls after cd
cdl()
{
    builtin cd "$@" && \
        if [ $(ls | wc -l) -le 25 ]; then
            ls --color --group-directories-first
        fi
}

# just heck it all
heck()
{
    sudo $(fc -nlr | sed 1q)
}

settitle()
{
    echo -ne "\ek$1\e\\"
}
