#!/bin/sh
# functions

autogit()
{
    git add --all && git commit -m "$1" && git push -u origin master
}

autofont()
{
    bdftopcf $1.bdf -o $1.pcf && \
        mkfontscale && \
        mkfontdir && \
        xset fp rehash && \
        fc-cache -fv
}

conf()
{
    case $1 in
        vim|v) $EDITOR ~/.vimrc ;;
        ncmpcpp|n) $EDITOR ~/.ncmpcpp/config ;;
        xrdb|x) $EDITOR ~/.Xresources ;;
        sxhkd|sxhkdrc|s) $EDITOR ~/.config/sxhkd/common ;;
        w|weechat) $EDITOR ~/.weechat/weechat.conf ;;
        2bwm|2) $EDITOR ~/src/pkg/2bwm/config.h
    esac
}

src()
{
    case $1 in
        vim|v) source ~/.vimrc ;;
        shell|sh|s) source ~/.bashrc ;;
        xrdb|x) xrdb ~/.Xresources ;;
        2bwm|2) prev=$(pwd) && \
            cd ~/src/pkg/2bwm && \
            make && sudo make install && \
            cd $prev ;;
    esac
}

heck()
{
    sudo $(fc -nlr | sed 1q)
}

extract()
{
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2) tar xvjf $1 ;;
            *.tar.gz) tar xvzf $1 ;;
            *.bz2) bunzip2 $1 ;;
            *.gz) gunzip $1 ;;
            *.tar) tar xvf $1 ;;
            *.tbz2) tar xvjf $1 ;;
            *.tgz) tar xvzf $1 ;;
            *.xz) unxz $1 ;;
            *.zip) unzip $1 ;;
            *.Z) uncompress $1 ;;
            *) echo 'cannot be extracted' ;;
        esac
    else
        echo 'not valid file'
    fi
}
