#!/usr/bin/env bash
# functions

# auto compile fonts
autofont()
{
    bdftopcf $1.bdf -o $1.pcf && \
        mkfontscale && \
        mkfontdir && \
        xset fp rehash && \
        fc-cache -fv
}

# quick access to config files
conf()
{
    case $1 in
        e|editor)
            $EDITOR ~/.config/nvim/init.vim ;;
        ncmpcpp|n)
            $EDITOR ~/.ncmpcpp/config ;;
        xrdb|x)
            $EDITOR ~/.Xresources ;;
        sxhkd|sxhkdrc|s)
            $EDITOR ~/.config/sxhkd/common ;;
        w|weechat)
            $EDITOR ~/.weechat/weechat.conf ;;
        t|tmux)
            $EDITOR ~/.tmux.conf ;;
        2bwm|2)
            $EDITOR ~/src/pkg/2bwm/config.h ;;
    esac
}

# source files and stuff
src()
{
    case $1 in
        shell|sh|s)
            source ~/.bashrc ;;
        xrdb|x)
            xrdb ~/.Xresources ;;
        2bwm|2)
            prev=$(pwd) && \
            cd ~/src/pkg/2bwm && \
            make && sudo make install && \
            cd $prev ;;
    esac
}

# ls after cd
cdl()
{
    builtin cd "$@" && \
        if [ $(ls | wc -l) -le 50 ]; then
            ls --color --group-directories-first
        fi
}

# just heck it all
heck()
{
    sudo $(fc -nlr | sed 1q)
}

settitle()
{
    echo -ne "\ek$1\e\\"
}
