#!/bin/sh
# set prompt

_dir()
{
    # replace $HOME with nothing (so just the prompt char)
    currentdir=${PWD/$HOME/}

    test -n currentdir && printf "$(basename 2>/dev/null "$currentdir")"
}

PS1='$(tput setaf 1)$(_dir);$(tput sgr0) '
